version: 1
default_environment: dev
project_id: 212865cf-084c-4bb8-a051-85e7a4e680fd
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-github
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-github.git
schedules:
- name: daily-refresh
  job: daily-refresh-job
  interval: '@daily'  # Can be @daily, @hourly, etc., or a cron-based interval
jobs:
- name: daily-refresh-job
  tasks:
  # Update this section to include any EL jobs or other
  # commands that you'd like to run:
  - tap-gitlab target-snowflake
